version: "3"
services:
  backend:
    image: yennu1402/todo-backend:latest
    container_name: todo-backend
    ports:
      - "3000:3000"
    networks:
      - todo-net

  frontend:
    image: yennu1402/todo-frontend:latest
    container_name: todo-frontend
    ports:
      - "8000:80"
    networks:
      - todo-net
    depends_on:
      - backend

networks:
  todo-net:
    driver: bridge
